# Generated by Django 2.2.4 on 2020-01-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('oily', models.CharField(choices=[('O', 'O'), ('X', 'X')], max_length=2, null=True)),
                ('dry', models.CharField(choices=[('O', 'O'), ('X', 'X')], max_length=2, null=True)),
                ('sensitive', models.CharField(choices=[('O', 'O'), ('X', 'X')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageId', models.TextField()),
                ('name', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('all', 'all'), ('male', 'male'), ('female', 'female')], max_length=10)),
                ('category', models.CharField(choices=[('skincare', 'skincare'), ('maskpack', 'maskpack'), ('suncare', 'suncare'), ('basemakeup', 'basemakeup')], max_length=20)),
                ('ingredients', models.TextField()),
                ('monthlySales', models.IntegerField(default=0)),
                ('oily', models.IntegerField(null=True)),
                ('dry', models.IntegerField(null=True)),
                ('sensitive', models.IntegerField(null=True)),
            ],
        ),
    ]
